"""pybracket — a storage-agnostic, game-agnostic tournament bracket library."""

from __future__ import annotations

from .advancement import (
    UnwindSignal,
    get_match,
    get_participant,
    get_placements,
    get_ready_matches,
    get_winner,
    is_complete,
    report_choice,
    report_game,
    report_result,
    unwind_game,
    unwind_result,
)
from .errors import (
    BracketStateError,
    InvalidResultError,
    MatchNotFoundError,
    ParticipantNotFoundError,
    PybracketError,
    ReseedError,
    SwissRoundIncompleteError,
    ValidationError,
)
from .formats import (
    advance_swiss_round,
    generate_double_elim,
    generate_gauntlet,
    generate_round_robin,
    generate_single_elim,
    generate_swiss,
)
from .models import (
    ALL_PLACES,
    EACH_GROUP,
    AdvancementType,
    Bracket,
    BracketFormat,
    BracketSide,
    BracketState,
    Game,
    Match,
    MatchStatus,
    PairingMethod,
    Participant,
    Phase,
    PhaseSpec,
    Placement,
    Qualification,
    Ranked,
    Round,
    SlotRef,
    Standing,
    Tournament,
)
from .operations import publish_bracket, reseed, set_best_of
from .seeding import (
    ByeCompletion,
    ByeProfile,
    allowable_bye_options,
    complete_bye_rounds,
)
from .tiebreakers import (
    AccumulatedTiebreaker,
    BuchholzTiebreaker,
    HeadToHeadTiebreaker,
    MiniLeagueTiebreaker,
    StatTiebreaker,
    Tiebreaker,
    WinCountTiebreaker,
    get_standings,
)
from .tournament import (
    advance_phase,
    all_of,
    dependent_phases,
    draft_phase,
    edit_changes_advancement,
    edit_phase_result,
    generate_tournament,
    is_phase_draftable,
    phase_is_complete,
    phase_results,
    place,
    places,
    preview_phase,
    publish_phase,
    revert_phase,
    top,
    top_of_each_group,
    unwind_phase_result,
)
from .utils import (
    bracket_from_dict,
    bracket_from_json,
    bracket_to_dict,
    bracket_to_json,
    next_power_of_2,
    recommend_pool_count,
    recommend_swiss_rounds,
    tournament_from_dict,
    tournament_from_json,
    tournament_to_dict,
    tournament_to_json,
)

__version__ = "0.1.0"

__all__ = [
    # Models
    "AdvancementType",
    "Bracket",
    "BracketFormat",
    "BracketSide",
    "BracketState",
    "Game",
    "Match",
    "MatchStatus",
    "PairingMethod",
    "Participant",
    "Placement",
    "Round",
    "Standing",
    # Generation
    "generate_single_elim",
    "generate_double_elim",
    "generate_round_robin",
    "generate_swiss",
    "generate_gauntlet",
    # Multi-stage tournaments
    "Tournament",
    "Phase",
    "PhaseSpec",
    "Qualification",
    "SlotRef",
    "Ranked",
    "ALL_PLACES",
    "EACH_GROUP",
    "generate_tournament",
    "draft_phase",
    "preview_phase",
    "publish_phase",
    "revert_phase",
    "advance_phase",
    "phase_results",
    "phase_is_complete",
    "is_phase_draftable",
    "dependent_phases",
    "edit_changes_advancement",
    "edit_phase_result",
    "unwind_phase_result",
    "all_of",
    "top",
    "top_of_each_group",
    "places",
    "place",
    # Byes
    "allowable_bye_options",
    "complete_bye_rounds",
    "ByeCompletion",
    "ByeProfile",
    # Result reporting
    "report_result",
    "report_game",
    "report_choice",
    "unwind_result",
    "unwind_game",
    "UnwindSignal",
    # Querying
    "get_ready_matches",
    "get_standings",
    "get_placements",
    "is_complete",
    "get_winner",
    "get_participant",
    "get_match",
    # Swiss
    "recommend_swiss_rounds",
    "advance_swiss_round",
    # Reseeding / config
    "publish_bracket",
    "reseed",
    "set_best_of",
    # Tiebreakers
    "Tiebreaker",
    "WinCountTiebreaker",
    "HeadToHeadTiebreaker",
    "BuchholzTiebreaker",
    "StatTiebreaker",
    "AccumulatedTiebreaker",
    "MiniLeagueTiebreaker",
    # Utilities
    "next_power_of_2",
    "recommend_pool_count",
    "bracket_to_dict",
    "bracket_from_dict",
    "bracket_to_json",
    "bracket_from_json",
    "tournament_to_dict",
    "tournament_from_dict",
    "tournament_to_json",
    "tournament_from_json",
    # Errors
    "PybracketError",
    "BracketStateError",
    "MatchNotFoundError",
    "ParticipantNotFoundError",
    "InvalidResultError",
    "ReseedError",
    "SwissRoundIncompleteError",
    "ValidationError",
]
